project:
  type: website

website:
  title: "Subsidy Map"
  navbar: false

format:
  html:
    theme: [cosmo, styles.scss]
    toc: false
    grid:
      sidebar-width: 0px
      body-width: 1400px
      margin-width: 0px

execute: 
  echo: false
  message: false
  warning: false
  error: false
